import * as T from 'three';
import {QUALITY} from './quality.js';
export const FACE_NORMALS={1:[1,0,0],6:[-1,0,0],2:[0,1,0],5:[0,-1,0],3:[0,0,1],4:[0,0,-1]};
const dots={1:[[0,0]],2:[[-1,1],[1,-1]],3:[[-1,1],[0,0],[1,-1]],4:[[-1,1],[1,1],[-1,-1],[1,-1]],5:[[-1,1],[1,1],[0,0],[-1,-1],[1,-1]],6:[[-1,1],[1,1],[-1,0],[1,0],[-1,-1],[1,-1]]};
function geometry(){const s=new T.Shape();s.moveTo(-.43,-.43);s.lineTo(.43,-.43);s.lineTo(.43,.43);s.lineTo(-.43,.43);s.closePath();const g=new T.ExtrudeGeometry(s,{depth:.86,bevelEnabled:true,bevelSize:.065,bevelThickness:.065,bevelSegments:1,steps:1});g.translate(0,0,-.43);return g;}
function die(color){const group=new T.Group(),body=new T.Mesh(geometry(),new T.MeshStandardMaterial({color,roughness:.35,flatShading:true}));body.castShadow=true;body.receiveShadow=true;group.add(body);const pipMat=new T.MeshStandardMaterial({color:0xfff7e3,roughness:.6});for(const [face,normal] of Object.entries(FACE_NORMALS)){const q=new T.Quaternion().setFromUnitVectors(new T.Vector3(0,0,1),new T.Vector3(...normal));for(const [x,y] of dots[face]){const pip=new T.Mesh(new T.CircleGeometry(.071,12),pipMat);pip.position.set(x*.23,y*.23,.501).applyQuaternion(q);pip.quaternion.copy(q);group.add(pip);}}return group;}
const faceQuaternion=value=>new T.Quaternion().setFromAxisAngle(new T.Vector3(0,1,0),.24).multiply(new T.Quaternion().setFromUnitVectors(new T.Vector3(...FACE_NORMALS[value]),new T.Vector3(0,1,0)));
export class DiceTray{
 constructor(container,quality='standard'){this.quality=quality;this.lastFrame=0;this.container=container;this.scene=new T.Scene();this.camera=new T.PerspectiveCamera(34,1,.1,30);this.camera.position.set(1.9,3.8,4.2);this.camera.lookAt(0,.2,0);this.renderer=new T.WebGLRenderer({antialias:true,alpha:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;this.renderer.setClearColor(0,0);this.renderer.toneMapping=T.ACESFilmicToneMapping;container.append(this.renderer.domElement);this.scene.add(new T.HemisphereLight(0xffffff,0x314153,3));const light=new T.DirectionalLight(0xffeac3,4);light.position.set(-2,7,3);light.castShadow=true;light.shadow.mapSize.set(512,512);this.scene.add(light);const floor=new T.Mesh(new T.BoxGeometry(5.1,.12,2.75),new T.MeshStandardMaterial({color:0x244653,roughness:.9}));floor.position.y=-.08;floor.receiveShadow=true;this.scene.add(floor);for(const z of [-1.42,1.42]){const edge=new T.Mesh(new T.BoxGeometry(5.35,.26,.12),new T.MeshStandardMaterial({color:0xc4a879}));edge.position.set(0,.01,z);this.scene.add(edge);}this.dice=[die(0x339fe8),die(0xf27563)];this.dice.forEach((d,i)=>{d.position.set(i?1:-1,.51,0);this.scene.add(d);});this.present(null,2);this.observer=new ResizeObserver(()=>this.resize());this.observer.observe(container);this.setQuality(quality);this.resize();this.frame=this.frame.bind(this);requestAnimationFrame(this.frame);}
 setQuality(name){this.quality=QUALITY[name]?name:'standard';const q=QUALITY[this.quality];this.renderer.setPixelRatio(Math.min(devicePixelRatio,q.diceRatio));this.renderer.shadowMap.enabled=q.shadows;this.scene.traverse(o=>{if(o.material)o.material.needsUpdate=true;});this.resize();}
 resize(){const w=this.container.clientWidth,h=this.container.clientHeight;if(w&&h){this.renderer.setSize(w,h);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();}}
 present(values,count=2,actor='blue'){this.count=count;this.actor=actor;this.animation=null;this.dice.forEach((d,i)=>{d.visible=i<count;d.position.set(count===1?0:i?1:-1,.51,0);d.children[0].material.color.set(i===0?(actor==='red'?0xf27563:0x339fe8):(actor==='red'?0x339fe8:0xf27563));d.quaternion.copy(faceQuaternion(values?.[i]||[3,5][i]));});}
 roll(values,power=.6){this.animation={start:performance.now(),duration:1100+power*350,values,from:this.dice.map(d=>d.quaternion.clone()),end:values.map(faceQuaternion),power};return new Promise(resolve=>this.resolve=resolve);}
 topFaces(){return this.dice.filter(d=>d.visible).map(d=>Object.entries(FACE_NORMALS).map(([face,n])=>({face:Number(face),y:new T.Vector3(...n).applyQuaternion(d.quaternion).y})).sort((a,b)=>b.y-a.y)[0].face);}
 frame(now){requestAnimationFrame(this.frame);if(document.hidden||now-this.lastFrame<1000/QUALITY[this.quality].fps-1)return;this.lastFrame=now;const a=this.animation;if(a){const t=Math.min(1,(now-a.start)/a.duration);this.dice.forEach((d,i)=>{if(!d.visible)return;const x=this.count===1?0:i?1:-1;d.position.set(x+Math.sin(t*Math.PI*3+i)*.5*(1-t),.51+Math.abs(Math.sin(t*Math.PI*4))*(1-t)*(1.2+a.power),Math.sin(t*Math.PI*4+i)*.35*(1-t));if(t<.72)d.rotation.set(t*19+i,t*23-i,t*17);else d.quaternion.slerp(a.end[i],Math.min(1,(t-.72)/.28));});if(t>=1){this.dice.forEach((d,i)=>{if(d.visible){d.quaternion.copy(a.end[i]);d.position.set(this.count===1?0:i?1:-1,.51,0);}});this.animation=null;this.resolve?.();this.resolve=null;}}
 if(this.container.offsetParent!==null)this.renderer.render(this.scene,this.camera);}
}
